apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- name: dragnet.kubemod.io
  failurePolicy: Ignore
  reinvocationPolicy: IfNeeded
  matchPolicy: Equivalent
  sideEffects: None

  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - '*'
    resources:
    - namespaces
    - persistentvolumeclaims
    - services
    - deployments
    operations:
    - CREATE
    - UPDATE
    scope: '*'

  namespaceSelector:
    matchExpressions:
      - key: kubemod-system-namespace
        operator: NotIn
        values: ["true"]
