apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
