name: 'Master Workflow'

on:
  push:
    branches:
      - '3-switch-to-github-actions'

jobs:

  deploy:
    name: Test and deploy latest master
    runs-on: ubuntu-latest

    steps:

      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.7'

      - uses: actions/checkout@v2


      - name: Deploy Latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          KUBEMOD_IMAGE_VERSION: latest

        run: |
          ./build/deploy-image.sh
          bash <(curl -s https://codecov.io/bash)
